
import type { Tutor } from './types';

const now = new Date();

export const tutors: Tutor[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'PhD in Mathematics with 10+ years of teaching experience. Making math intuitive and fun!',
    subjects: ['Mathematics', 'Physics', 'Calculus'],
    rating: 2.8,
    reviewsCount: 128,
    hourlyRate: 75,
    experience: 12,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: false,
    bio: "Hello! I'm Dr. Evelyn Reed. I believe that anyone can excel at math with the right guidance. My approach is to break down complex problems into simple, understandable steps. I have a PhD in Mathematics from Stanford University and have been helping students achieve their academic goals for over a decade. Whether you're struggling with algebra or tackling advanced calculus, I'm here to build your confidence and skills.",
    aiSummary: "Dr. Evelyn Reed is a highly-rated, experienced PhD in Mathematics specializing in making complex topics like calculus and physics accessible and engaging for students. Her teaching style focuses on building foundational understanding and confidence.",
    reviews: [
      { id: 'review-1-1', author: 'Alex Johnson', rating: 5, comment: "Dr. Reed is a lifesaver! I was completely lost in my calculus class, and she made everything click. Highly recommend!" },
      { id: 'review-1-2', author: 'Samantha Lee', rating: 5, comment: "An amazing tutor. Patient, knowledgeable, and truly cares about her students' success." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 10)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 10)).toISOString(),
  },
  {
    id: '2',
    name: 'Javier Morales',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'Concert violinist and dedicated instructor for all skill levels.',
    subjects: ['Violin', 'Music Theory'],
    rating: 3.0,
    reviewsCount: 92,
    hourlyRate: 90,
    experience: 15,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: true,
    bio: "Music is my life's passion, and I love sharing it with others. As a concert violinist who has performed with major orchestras, I bring a wealth of practical experience to my lessons. I teach students of all ages and abilities, from absolute beginners to advanced players looking to refine their technique. My lessons are tailored to your personal goals, whether you want to play for fun or prepare for auditions.",
    aiSummary: "Javier Morales is a top-rated concert violinist offering expert instruction in violin and music theory for all levels. His students benefit from his extensive performance experience and personalized, goal-oriented teaching method.",
    reviews: [
      { id: 'review-2-1', author: 'Michael Chen', rating: 5, comment: "Javier is an incredible teacher. My playing has improved more in the last six months than in the previous three years." },
      { id: 'review-2-2', author: 'Emily Davis', rating: 5, comment: "His passion for music is contagious. He makes learning the violin an absolute joy." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 5)).toISOString(),
  },
  {
    id: '3',
    name: 'Chloe Addison',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'Award-winning artist passionate about unlocking creativity through painting.',
    subjects: ['Oil Painting', 'Watercolor Painting', 'Art History'],
    rating: 2.5,
    reviewsCount: 76,
    hourlyRate: 60,
    experience: 8,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: true,
    bio: "Hi, I'm Chloe! I'm a professional artist with a Master of Fine Arts degree. I believe everyone has a creative spark, and my job is to help you find and nurture it. I specialize in oil and watercolor painting, but I also love discussing art history to give context to our work. My studio is a welcoming, judgment-free space where you can experiment, make mistakes, and grow as an artist.",
    aiSummary: "Chloe Addison is a professional artist with an MFA, specializing in oil and watercolor painting. She creates a supportive environment for students to explore their creativity, backed by a strong foundation in art history and technique.",
    reviews: [
      { id: 'review-3-1', author: 'Olivia Garcia', rating: 5, comment: "Chloe's classes are the highlight of my week. I've learned so much about color and composition." },
      { id: 'review-3-2', author: 'David Miller', rating: 4, comment: "Great instructor. Very knowledgeable and gives constructive feedback. Sometimes classes run a little over." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 20)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 20)).toISOString(),
  },
  {
    id: '4',
    name: 'Ben Carter',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'Patient and engaging English tutor specializing in literature and writing.',
    subjects: ['English', 'Literature', 'Creative Writing'],
    rating: 2.9,
    reviewsCount: 150,
    hourlyRate: 55,
    experience: 7,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: false,
    bio: "I'm Ben, a literature enthusiast with a Master's in English from Oxford. I specialize in helping students analyze literature, improve their essay writing, and find their own voice in creative writing. I focus on building critical thinking skills that extend beyond the classroom. My goal is to make literature less intimidating and more enjoyable for everyone.",
    aiSummary: "Ben Carter is a highly-rated English tutor with a Master's from Oxford. He excels at helping students with literature analysis, essay structure, and creative writing, focusing on building lasting critical thinking skills.",
    reviews: [
      { id: 'review-4-1', author: 'Sophia Rodriguez', rating: 5, comment: "Ben helped me so much with my college application essays. I couldn't have done it without him." },
      { id: 'review-4-2', author: 'James Wilson', rating: 5, comment: "He makes Shakespeare interesting! That's a miracle. Great tutor." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 1)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 1)).toISOString(),
  },
  {
    id: '5',
    name: 'Liam Goldberg',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'Juilliard graduate offering personalized piano lessons for all ages.',
    subjects: ['Piano', 'Music Theory'],
    rating: 2.7,
    reviewsCount: 112,
    hourlyRate: 85,
    experience: 10,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: true,
    bio: "Hello, my name is Liam. A graduate of The Juilliard School, I have dedicated my life to the art of the piano. I offer a structured yet flexible curriculum that covers everything from classical foundations to modern improvisation. My goal is to foster a lifelong love of music in each student.",
    aiSummary: "Liam Goldberg, a Juilliard-trained pianist, provides high-quality, personalized piano and music theory instruction. His structured approach caters to all ages, aiming to instill a deep and lasting appreciation for music.",
    reviews: [
      { id: 'review-5-1', author: 'Noah Kim', rating: 5, comment: "An absolutely phenomenal teacher. Liam's technical knowledge is matched only by his patience." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 8)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 8)).toISOString(),
  },
  {
    id: '6',
    name: 'Aisha Khan',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'Vocal coach for pop, rock, and musical theater styles.',
    subjects: ['Singing', 'Voice'],
    rating: 2.6,
    reviewsCount: 88,
    hourlyRate: 70,
    experience: 9,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: false,
    bio: "Unlock the power of your voice! I'm Aisha, a professional vocal coach with nearly a decade of experience helping singers improve their range, technique, and confidence. I create a fun, supportive environment where you can find your unique sound.",
    aiSummary: "Aisha Khan is a professional vocal coach specializing in contemporary styles like pop, rock, and theater. She focuses on technique, range, and confidence-building in a supportive and engaging lesson environment.",
    reviews: [
      { id: 'review-6-1', author: 'Isabella Rossi', rating: 5, comment: "Aisha is amazing! She helped me hit notes I never thought I could and prepared me for my first public performance." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 3)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 3)).toISOString(),
  },
  {
    id: '7',
    name: 'Dr. Marcus Chen',
    avatarUrl: 'https://placehold.co/150x150.png',
    headline: 'History professor making the past come alive.',
    subjects: ['History', 'Political Science'],
    rating: 2.4,
    reviewsCount: 130,
    hourlyRate: 65,
    experience: 20,
    availabilitySummary: "Contact for availability",
    availability: [],
    isOnline: true,
    isInPerson: false,
    bio: "As a university professor, I believe history is a story waiting to be told. I specialize in connecting historical events to current affairs, making the subject relevant and fascinating for students. I can help with exam prep, essay writing, and developing a deeper understanding of the world.",
    aiSummary: "Dr. Marcus Chen, a university history professor, excels at making history relevant and engaging. He assists students with exam preparation and essay writing by connecting past events to the present day.",
    reviews: [
      { id: 'review-7-1', author: 'Daniel Brown', rating: 5, comment: "Dr. Chen is the best history teacher I've ever had, including my ones at school. He makes everything so clear and interesting." },
    ],
    createdAt: new Date(new Date().setDate(now.getDate() - 15)).toISOString(),
    updatedAt: new Date(new Date().setDate(now.getDate() - 15)).toISOString(),
  },
];
